### ISSUE TITLE
Add more names to the enemy list.

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Dungeon#1]
In the `/Enemy.java` file add more names.

```java
ENEMY_NAMES = { "Zombie", "Skeleton", "Warrior", "Goblin", "Werewolf", "Vampire" }
```

**Comment by NayakNavin** [comment]
can you be more specific like how many names you want ?

**Comment by maaslalani** [comment]
@NayakNavin Perhaps 20 total

**Comment by DreamyPhobic** [comment]
@maaslalani Can I work on this issue?

**Comment by EikeSan** [comment]
@maaslalani How i contribute to ur repo?

**Comment by AjaySharvesh3** [comment]
Shall I work on this?

**Comment by DreamyPhobic** [comment]
Sorry @AjaySharvesh3 , I had already submitted a PR.
