### ISSUE TITLE
Give enemies special abilities.

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Dungeon#2]
For different types of enemies, give them different abilities.
For example:
* `Skeletons` are harder to hit (less chance of hitting them)
* `Goblins` can steal your coins
* `Warriors` should generally have more `health` and deal more `damage`

**Comment by pranav1698** [comment]
Heya maaslalani, 
I would like to work on this issue

**Comment by pranav1698** [comment]
I think so that `less chance of hitting` them means less damage on them

**Comment by jnakshansh** [comment]
Vampire has ability to become invisible for certain period.
Werewolf can recover from hard damage in less time.

**Comment by AlecsFerra** [comment]
Done #18
