### ISSUE TITLE
Give player special power-ups.

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Dungeon#3]
For example
* `invisibility`: player cannot take damage for certain time.
* `flee`: player does not lose health for running away for a certain number of flees.
* `mind reader`: the player can see in advanced how much damage the enemy will deal and can choose to run away or fight.

Feel free to come up with more on your own!

**Comment by sennahLessert** [comment]
i'll give it a try

**Comment by vincentvvv** [comment]
Woops didn't see that your PR was for invisibility :/, but I also did the same haha https://github.com/maaslalani/Dungeon/pull/25
